import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Sidebar from "@/components/layout/Sidebar";
import Section from "@/components/layout/Section";
const AudioPlayer = dynamic(() => import("@/components/Player/AudioPlayer"), {
  ssr: false,
});
import ReduxProvider from "@/components/ReduxProvider";
import dynamic from "next/dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <Sidebar />
          <Section>{children}</Section>
          <AudioPlayer />
        </ReduxProvider>
      </body>
    </html>
  );
}
